export default {
	first_name: "Yinon",
	last_name: "Yinon",
	middle_name: "Yinon",
	bDay: "Yinon",
	email: "Yinon",
	password: "Yinon",
	gender: "Yinon",
	address1: "Yinon",
	address2: "Yinon",
	street_name: "Yinon",
	street_number: "Yinon",
	city: "Yinon",
	state: "Yinon",
	country: "Yinon",
};
